channels:
- r
- bioconda
dependencies:
- samtools=1.3
- salmon=0.8.2
- star=2.5.3a
- fastqc=0.11.7
- multiqc=1.3
- trim-galore=0.4.4
- cutadapt=1.9.1
- bedtools=2.26.0
- ucsc-bedgraphtobigwig=332
- r=3.4.1
- r-dplyr
- r-ggplot2
- r-tidyr
- r-reshape2
- r-rjson
- bioconductor-limma
- bioconductor-edger
- bioconductor-tximport
- bioconductor-biostrings
- bioconductor-rtracklayer
- bioconductor-drimseq
