channels:
- r
- bioconda
- conda-forge
dependencies:
- samtools=1.8
- salmon=0.10.2
- star=2.6.0c
- fastqc=0.11.7
- multiqc=1.6a0
- trim-galore=0.5.0
- cutadapt=1.16
- bedtools=2.27.1
- ucsc-bedgraphtobigwig=366
- r=3.4.1
- r-dplyr= 0.7.4
- r-ggplot2
- r-tidyr
- r-reshape2
- r-rjson
- r-devtools
- r-r6=2.2.2
- r-glue=1.2.0
- r-tibble=1.4.2
- r-stringi=1.2.4
- bioconductor-limma
- bioconductor-edger
- bioconductor-tximport
- bioconductor-biostrings
- bioconductor-rtracklayer
- bioconductor-drimseq
- bioconductor-biocinstaller
- bioconductor-biocfilecache
- bioconductor-ensembldb


