#!/usr/bin Rscript

args <- (commandArgs(trailingOnly = TRUE))
for (i in seq_len(length(args))) {
  eval(parse(text = args[[i]]))
}

# Rprof(rprof_out)

library(numbat)
library(Seurat)
library(readr)
library(magrittr)
conflicted::conflict_prefer("rowSums", "Matrix")

matrix_dir = fs::path_dir(matrix_file)

count_mat <- Seurat::Read10X(matrix_dir)

if(!as.numeric(read_prop) == 1){
	count_mat <- scuttle::downsampleMatrix(count_mat, as.numeric(read_prop))
}

allele_df = data.table::fread(allele_df) %>%
    tidyr::drop_na(CHROM) %>% # drop X chromosome values
    # dplyr::mutate(CHROM = as.factor(CHROM)) %>%
  identity()

# normal_reference_mat = readRDS(normal_reference_mat)

# normal_reference_mat <- "~/single_cell_projects/resources/collin_et_al_2021_proj/output/numbat/count_mat.rds"
#
# normal_reference_mat = readRDS(normal_reference_mat)
#
# # normal_reference_mat <- normal_reference_mat[rownames(normal_reference_mat) %in% rownames(count_mat),]
#
# normal_cell_annot <-
# 	tibble::tibble(cell = colnames(normal_reference_mat)) %>%
# 	dplyr::mutate(group = "retina")
#
# ref_internal = numbat::aggregate_counts(normal_reference_mat, normal_cell_annot)

ref_path <- "~/Homo_sapiens/numbat/sridhar_ref.rds"

ref_internal <- readRDS(ref_path)

# count_mat <- count_mat[rownames(count_mat) %in% rownames(normal_reference_mat),]


# bulk = numbat:::get_bulk(
# 	count_mat = count_mat,
# 	lambdas_ref = ref_internal,
# 	df_allele = allele_df,
# 	gtf = gtf_hg38,
# 	genetic_map = genetic_map_hg38
# )
#
# segs_loh = bulk %>% numbat:::detect_clonal_loh(t = 1e-4)

segs_loh = NULL

# run
out = run_numbat(
	count_mat, # gene x cell integer UMI count matrix done
	lambdas_ref = ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix done
	allele_df, # allele dataframe generated by pileup_and_phase script done
	genome = "hg38",
	min_cells = 10,
	t = as.numeric(t),
	max_iter = as.integer(max_iter),
	max_entropy = max_entropy,
	segs_loh = segs_loh,
	min_LLR = min_LLR,
	init_k = 3,
	ncores = as.integer(ncores),
	plot = TRUE,
	multi_allelic = FALSE,
	common_diploid = TRUE,
	out_dir = out_dir,
	tau = as.numeric(tau),
	skip_nj = FALSE)

done_file <- fs::path(out_dir, "done.txt")

write(ref_path, file = done_file)
